# Generated by Django 4.2.28 on 2026-02-12 04:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='evidences/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('captured_at', models.DateTimeField()),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADING', 'Uploading'), ('SYNCED', 'Synced'), ('ERROR', 'Error')], default='PENDING', max_length=15)),
                ('mobile_id', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'evidences',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='signatures/')),
                ('signer_name', models.CharField(max_length=150)),
                ('signer_phone', models.CharField(blank=True, max_length=20)),
                ('signer_email', models.EmailField(blank=True, max_length=254)),
                ('mobile_id', models.CharField(blank=True, max_length=100)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'signatures',
            },
        ),
        migrations.CreateModel(
            name='SimulationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('INCIDENT', 'Incident'), ('FAILURE', 'Failure'), ('TEST', 'Test')], max_length=15)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PROCESSED', 'Processed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'simulation_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_token', models.CharField(db_index=True, help_text='Public token for customer tracking without login', max_length=32, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('service_location_address', models.TextField(blank=True, help_text='Service site address')),
                ('customer_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('customer_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending - Awaiting Assignment'), ('ASSIGNED', 'Assigned to Technician'), ('IN_TRANSIT', 'In Transit (Traveling to Site)'), ('IN_SERVICE', 'In Service (At Site)'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('mobile_id', models.CharField(blank=True, max_length=100)),
                ('offline_flag', models.BooleanField(default=False)),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending Sync'), ('SYNCING', 'Syncing'), ('SYNCED', 'Synced'), ('CONFLICT', 'Conflict')], default='PENDING', max_length=15)),
                ('customer_signature_required', models.BooleanField(default=True)),
                ('evidence_photos_required', models.BooleanField(default=True)),
                ('materials_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'work_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
