# Generated by Django 4.2.27 on 2026-02-04 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='technician',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TECHNICIAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signature',
            name='work_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='ordenes.workorder'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='ordenes.workorder'),
        ),
    ]
