# Generated by Django 4.2.28 on 2026-02-12 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenes', '0001_initial'),
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='usuarios.company'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='clientes.customer'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='service_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order', to='clientes.servicerequest'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='technician',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TECHNICIAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signature',
            name='work_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='ordenes.workorder'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='ordenes.workorder'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['company', 'status'], name='work_orders_company_8cd492_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['technician', 'status'], name='work_orders_technic_50e3f3_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['tracking_token'], name='work_orders_trackin_8481dd_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['mobile_id'], name='work_orders_mobile__b5f957_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['-created_at'], name='work_orders_created_0d158a_idx'),
        ),
        migrations.AddIndex(
            model_name='signature',
            index=models.Index(fields=['work_order'], name='signatures_work_or_9da270_idx'),
        ),
        migrations.AddIndex(
            model_name='signature',
            index=models.Index(fields=['mobile_id'], name='signatures_mobile__0d436a_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['work_order', 'sync_status'], name='evidences_work_or_8775fa_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['mobile_id'], name='evidences_mobile__722338_idx'),
        ),
    ]
