# Generated by Django 4.2.28 on 2026-02-12 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedmaterial',
            name='photos',
            field=models.ManyToManyField(blank=True, help_text='Photos of materials in use for verification', to='ordenes.evidence'),
        ),
        migrations.AddField(
            model_name='usedmaterial',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_materials', to='ordenes.workorder'),
        ),
        migrations.AddField(
            model_name='technicianinventory',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_inventories', to='inventario.material'),
        ),
    ]
