# Generated by Django 4.2.28 on 2026-02-12 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
        ('ordenes', '0001_initial'),
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianinventory',
            name='technician',
            field=models.ForeignKey(limit_choices_to={'role': 'TECHNICIAN'}, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restockhistory',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restock_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restockhistory',
            name='related_approval',
            field=models.ForeignKey(blank=True, help_text='If related to material approval', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.materialapproval'),
        ),
        migrations.AddField(
            model_name='restockhistory',
            name='related_work_order',
            field=models.ForeignKey(blank=True, help_text='If related to work order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordenes.workorder'),
        ),
        migrations.AddField(
            model_name='restockhistory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_history', to='inventario.centralwarehouse'),
        ),
        migrations.AddField(
            model_name='materialapproval',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialapproval',
            name='used_material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='inventario.usedmaterial'),
        ),
        migrations.AddField(
            model_name='materialapproval',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_approvals', to='ordenes.workorder'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['is_active'], name='materials_is_acti_c341ca_idx'),
        ),
        migrations.AddField(
            model_name='centralwarehouse',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='central_warehouse', to='usuarios.company'),
        ),
        migrations.AddField(
            model_name='centralwarehouse',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stock', to='inventario.material'),
        ),
        migrations.AddIndex(
            model_name='usedmaterial',
            index=models.Index(fields=['work_order'], name='used_materi_work_or_d1bce4_idx'),
        ),
        migrations.AddIndex(
            model_name='usedmaterial',
            index=models.Index(fields=['mobile_id'], name='used_materi_mobile__404ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianinventory',
            index=models.Index(fields=['technician'], name='technician__technic_17c6c2_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianinventory',
            index=models.Index(fields=['mobile_id'], name='technician__mobile__c35aee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='technicianinventory',
            unique_together={('technician', 'material')},
        ),
        migrations.AddIndex(
            model_name='restockhistory',
            index=models.Index(fields=['warehouse'], name='restock_his_warehou_dd6c10_idx'),
        ),
        migrations.AddIndex(
            model_name='restockhistory',
            index=models.Index(fields=['-created_at'], name='restock_his_created_40d8b0_idx'),
        ),
        migrations.AddIndex(
            model_name='restockhistory',
            index=models.Index(fields=['restock_type'], name='restock_his_restock_807adf_idx'),
        ),
        migrations.AddIndex(
            model_name='materialapproval',
            index=models.Index(fields=['work_order', 'status'], name='material_ap_work_or_77f345_idx'),
        ),
        migrations.AddIndex(
            model_name='materialapproval',
            index=models.Index(fields=['reviewed_by'], name='material_ap_reviewe_b62703_idx'),
        ),
        migrations.AddIndex(
            model_name='centralwarehouse',
            index=models.Index(fields=['company', 'material'], name='central_war_company_66513e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='centralwarehouse',
            unique_together={('company', 'material')},
        ),
    ]
