# Generated by Django 4.2.28 on 2026-03-10 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialapproval',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['OWNER', 'DISPATCHER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_approvals', to=settings.AUTH_USER_MODEL),
        ),
    ]
