# Generated by Django 4.2.28 on 2026-03-10 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='usuarios.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner (Business Owner)'), ('DISPATCHER', 'Dispatcher (Operations Manager)'), ('TECHNICIAN', 'Technician (Field Worker)')], default='TECHNICIAN', max_length=15),
        ),
    ]
