# Generated by Django 4.2.28 on 2026-02-12 04:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationGeoFence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expected_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('expected_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('radius_meters', models.IntegerField(default=100)),
                ('is_validated', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'location_geofences',
            },
        ),
        migrations.CreateModel(
            name='TechnicianLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('accuracy_meters', models.IntegerField(blank=True, null=True)),
                ('mobile_id', models.CharField(blank=True, max_length=100)),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending Sync'), ('SYNCED', 'Synced')], default='PENDING', max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'technician_locations',
                'ordering': ['-timestamp'],
            },
        ),
    ]
