# Generated by Django 4.2.27 on 2026-02-04 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianlocation',
            name='technician',
            field=models.ForeignKey(limit_choices_to={'role': 'TECHNICIAN'}, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL),
        ),
    ]
