# Generated by Django 4.2.28 on 2026-02-12 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0001_initial'),
        ('ordenes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianlocation',
            name='technician',
            field=models.ForeignKey(limit_choices_to={'role': 'TECHNICIAN'}, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicianlocation',
            name='work_order',
            field=models.ForeignKey(blank=True, help_text='Work order being serviced when location was recorded', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technician_locations', to='ordenes.workorder'),
        ),
        migrations.AddField(
            model_name='locationgeofence',
            name='work_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geofence', to='ordenes.workorder'),
        ),
        migrations.AddIndex(
            model_name='technicianlocation',
            index=models.Index(fields=['technician', '-timestamp'], name='technician__technic_933580_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianlocation',
            index=models.Index(fields=['work_order'], name='technician__work_or_f86952_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianlocation',
            index=models.Index(fields=['mobile_id'], name='technician__mobile__dc7e7d_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianlocation',
            index=models.Index(fields=['sync_status'], name='technician__sync_st_ca491e_idx'),
        ),
    ]
