export const sidebarItems = [
  {
    key: "platform",
    label: "Plataforma",
    icon: "PiBriefcaseFill",
    wordkeys: ["plataforma", "empresas", "admin"],
    defaultOpen: true,
    children: [
      {
        key: "companies",
        label: "Empresas",
        icon: "PiBriefcaseFill",
        wordkeys: ["empresas", "companias", "clientes b2b", "tenants"],
        superuserOnly: true,
        permission: "view.companies.option",
        path: "/companies",
      },
    ],
  },
  {
    key: "operations",
    label: "Operaciones",
    icon: "PiGridFourFill",
    wordkeys: ["operaciones", "resumen", "campo"],
    defaultOpen: true,
    children: [
      {
        key: "dashboard",
        label: "Resumen",
        icon: "PiHouseFill",
        wordkeys: ["dashboard", "tablero", "inicio", "resumen"],
        roles: ["OWNER", "DISPATCHER"],
        hideForSuperuser: true,
        path: "/dashboard",
      },
      {
        key: "inventory",
        label: "Inventario",
        icon: "PiPackageFill",
        wordkeys: ["inventario", "stock", "materiales"],
        roles: ["OWNER", "DISPATCHER"],
        hideForSuperuser: true,
        path: "/inventory",
      },
      {
        key: "customers",
        label: "Clientes",
        icon: "PiUsersFill",
        wordkeys: ["clientes", "historial", "customer"],
        roles: ["OWNER", "DISPATCHER"],
        hideForSuperuser: true,
        path: "/customers",
      },
    ],
  },
  {
    key: "dispatch",
    label: "Despacho",
    icon: "PiClipboardTextFill",
    wordkeys: ["despacho", "ordenes", "asignaciones", "solicitudes", "evidencias"],
    roles: ["DISPATCHER"],
    hideForSuperuser: true,
    defaultOpen: true,
    children: [
      {
        key: "work-orders",
        label: "Órdenes",
        icon: "PiClipboardTextFill",
        wordkeys: ["ordenes", "ordenes de trabajo", "crear orden"],
        path: "/work-orders",
      },
      {
        key: "assignments",
        label: "Asignaciones",
        icon: "PiClipboardTextFill",
        wordkeys: ["asignaciones", "tareas", "despacho"],
        path: "/assignments",
      },
      {
        key: "service-requests",
        label: "Solicitudes",
        icon: "PiClipboardTextFill",
        wordkeys: ["solicitudes", "servicios", "validacion"],
        path: "/service-requests",
      },
      {
        key: "materials-approval",
        label: "Evidencias",
        icon: "PiCameraFill",
        wordkeys: ["evidencias", "materiales", "fotos"],
        path: "/materials-approval",
      },
    ],
  },
  {
    key: "team",
    label: "Equipo",
    icon: "PiUsersThreeFill",
    wordkeys: ["equipo", "usuarios", "tecnicos", "personal"],
    children: [
      {
        key: "team-owner",
        label: "Personal",
        icon: "PiUsersThreeFill",
        roles: ["OWNER"],
        hideForSuperuser: true,
        permission: "view.users.option",
        wordkeys: ["usuarios", "equipo", "tecnicos", "staff"],
        path: "/users",
      },
      {
        key: "team-dispatcher",
        label: "Técnicos",
        icon: "PiUsersThreeFill",
        roles: ["DISPATCHER"],
        hideForSuperuser: true,
        permission: "view.users.option",
        wordkeys: ["usuarios", "equipo", "tecnicos", "staff"],
        path: "/users",
      },
    ],
  },
  {
    key: "field",
    label: "Trabajo en campo",
    icon: "PiCalendarCheckFill",
    wordkeys: ["agenda", "tecnico", "campo", "ordenes"],
    children: [
      {
        key: "agenda",
        label: "Mi agenda",
        icon: "PiCalendarCheckFill",
        wordkeys: ["agenda", "ordenes asignadas", "evidencia", "inventario"],
        roles: ["TECHNICIAN"],
        hideForSuperuser: true,
        path: "/agenda",
      },
    ],
  },
  {
    key: "account",
    label: "Cuenta",
    icon: "PiUserFill",
    wordkeys: ["perfil", "usuario", "cuenta"],
    children: [
      {
        key: "profile",
        label: "Perfil",
        icon: "PiUserFill",
        wordkeys: ["perfil", "usuario", "cuenta"],
        path: "/profile",
      },
    ],
  },
];
