export const sidebarItems = [
  {
    key: "operations",
    label: "Operaciones",
    icon: "PiGridFourFill",
    wordkeys: ["operaciones", "operacion", "operación", "cockpit", "campo"],
    defaultOpen: true,
    children: [
      {
        key: "dashboard",
        label: "Dashboard",
        icon: "PiHouseFill",
        wordkeys: ["dashboard", "inicio", "home"],
        path: "/dashboard",
      },
      {
        key: "service-requests",
        label: "Solicitudes",
        icon: "PiClipboardTextFill",
        wordkeys: ["solicitudes", "request", "servicio"],
        path: "/service-requests",
      },
      {
        key: "inventory",
        label: "Inventario",
        icon: "PiPackageFill",
        wordkeys: ["inventario", "stock", "almacen", "almacén"],
        path: "/inventory",
      },
      {
        key: "materials-approval",
        label: "Evidencias",
        icon: "PiCameraFill",
        wordkeys: ["evidencias", "materiales", "fotos"],
        path: "/materials-approval",
      },
      {
        key: "customers",
        label: "Clientes",
        icon: "PiUsersFill",
        wordkeys: ["clientes", "customer", "historial"],
        path: "/customers",
      },
      {
        key: "simulator",
        label: "Simulador",
        icon: "PiFlaskFill",
        wordkeys: ["simulador", "escenarios", "pruebas"],
        roles: ["OWNER"],
        path: "/simulator",
      },
    ],
  },
  {
    key: "administration",
    label: "Administración",
    icon: "PiBriefcaseFill",
    roles: ["OWNER"],
    wordkeys: [
      "admin",
      "administracion",
      "administración",
      "configuracion",
      "configuración",
      "control",
    ],
    children: [
      {
        key: "users",
        label: "Usuarios",
        icon: "PiUsersThreeFill",
        permission: "view.users.option",
        wordkeys: ["usuarios", "users", "staff"],
        path: "/users",
      },
      {
        key: "roles-permissions",
        label: "Roles y permisos",
        icon: "PiUserGearFill",
        permission: "view.roles.option",
        wordkeys: ["roles", "permisos", "roles y permisos"],
        path: "/roles-permissions",
      },
      {
        key: "subscription",
        label: "Suscripción",
        icon: "PiCreditCardFill",
        wordkeys: ["suscripcion", "suscripción", "plan", "pago"],
        path: "/subscription",
      },
      {
        key: "log",
        label: "Log",
        icon: "PiClockCounterClockwiseFill",
        permission: "view.log.option",
        wordkeys: ["log", "bitacora", "movimientos"],
        path: "/log",
      },
      {
        key: "release-notes",
        label: "Notas de versión",
        icon: "PiKeyFill",
        permission: "release_notes.general.manage_release_notes",
        wordkeys: ["notas", "version", "versión", "release"],
        path: "/release-notes",
      },
    ],
  },
  {
    key: "account",
    label: "Cuenta",
    icon: "PiUserFill",
    wordkeys: ["perfil", "usuario", "cuenta", "ajustes"],
    children: [
      {
        key: "profile",
        label: "Perfil",
        icon: "PiUserFill",
        wordkeys: ["perfil", "usuario", "cuenta"],
        path: "/profile",
      },
    ],
  },
];
