import {
  COMPANY_ROLE,
  SUPERVISOR_ROLE,
  TECHNICIAN_ROLE,
} from "@utils/constants/roles";

export const sidebarItems = [
  {
    key: "platform",
    label: "Admin",
    icon: "PiBriefcaseFill",
    wordkeys: ["admin", "plataforma", "empresas", "roles", "log"],
    defaultOpen: true,
    superuserOnly: true,
    permission: "view.admin.menu",
    children: [
      {
        key: "companies",
        label: "Empresas",
        icon: "PiBriefcaseFill",
        wordkeys: ["empresas", "companias", "clientes b2b", "tenants"],
        superuserOnly: true,
        permission: "view.companies.option",
        path: "/companies",
      },
      {
        key: "roles-permissions",
        label: "Roles y permisos",
        icon: "PiGridFourFill",
        wordkeys: ["roles", "permisos", "matriz"],
        superuserOnly: true,
        permission: "view.roles.option",
        path: "/roles-permissions",
      },
      {
        key: "release-notes",
        label: "Notas de versión",
        icon: "PiClipboardTextFill",
        wordkeys: ["release", "version", "notas"],
        superuserOnly: true,
        permission: "view.release_notes.option",
        path: "/release-notes",
      },
      {
        key: "log",
        label: "Log",
        icon: "PiClipboardTextFill",
        wordkeys: ["log", "eventos", "bitacora"],
        superuserOnly: true,
        permission: "view.log.option",
        path: "/log",
      },
    ],
  },
  {
    key: "company",
    label: "Empresa",
    icon: "PiGridFourFill",
    wordkeys: ["empresa", "resumen", "clientes", "usuarios", "suscripcion"],
    defaultOpen: true,
    roles: [COMPANY_ROLE, SUPERVISOR_ROLE],
    hideForSuperuser: true,
    children: [
      {
        key: "dashboard",
        label: "Resumen",
        icon: "PiHouseFill",
        wordkeys: ["dashboard", "tablero", "inicio", "resumen"],
        roles: [COMPANY_ROLE, SUPERVISOR_ROLE],
        path: "/dashboard",
      },
      {
        key: "team-owner",
        label: "Personal",
        icon: "PiUsersThreeFill",
        roles: [COMPANY_ROLE],
        permission: "view.users.option",
        wordkeys: ["usuarios", "equipo", "tecnicos", "técnicos", "staff"],
        path: "/users",
      },
      {
        key: "team-supervisor",
        label: "Técnicos",
        icon: "PiUsersThreeFill",
        roles: [SUPERVISOR_ROLE],
        permission: "view.users.option",
        wordkeys: ["usuarios", "equipo", "tecnicos", "técnicos", "staff"],
        path: "/users",
      },
      {
        key: "customers",
        label: "Clientes",
        icon: "PiUsersFill",
        wordkeys: ["clientes", "historial", "customer"],
        roles: [COMPANY_ROLE, SUPERVISOR_ROLE],
        path: "/customers",
      },
      {
        key: "inventory",
        label: "Inventario",
        icon: "PiPackageFill",
        wordkeys: ["inventario", "stock", "materiales"],
        roles: [COMPANY_ROLE, SUPERVISOR_ROLE],
        path: "/inventory",
      },
      {
        key: "subscription",
        label: "Suscripción",
        icon: "PiBriefcaseFill",
        wordkeys: ["suscripcion", "planes", "billing"],
        roles: [COMPANY_ROLE],
        permission: "view.subscription.option",
        path: "/subscription",
      },
    ],
  },
  {
    key: "operations",
    label: "Operaciones",
    icon: "PiClipboardTextFill",
    wordkeys: ["operaciones", "ordenes", "asignaciones", "solicitudes", "evidencias"],
    roles: [COMPANY_ROLE, SUPERVISOR_ROLE],
    hideForSuperuser: true,
    defaultOpen: true,
    children: [
      {
        key: "work-orders",
        label: "Órdenes",
        icon: "PiClipboardTextFill",
        wordkeys: ["ordenes", "ordenes de trabajo", "crear orden"],
        path: "/work-orders",
      },
      {
        key: "assignments",
        label: "Asignaciones",
        icon: "PiClipboardTextFill",
        wordkeys: ["asignaciones", "tareas", "despacho"],
        path: "/assignments",
      },
      {
        key: "service-requests",
        label: "Solicitudes",
        icon: "PiClipboardTextFill",
        wordkeys: ["solicitudes", "servicios", "validacion", "validación"],
        path: "/service-requests",
      },
      {
        key: "materials-approval",
        label: "Evidencias",
        icon: "PiCameraFill",
        wordkeys: ["evidencias", "materiales", "fotos"],
        path: "/materials-approval",
      },
    ],
  },
  {
    key: "field",
    label: "Trabajo en campo",
    icon: "PiCalendarCheckFill",
    wordkeys: ["agenda", "tecnico", "técnico", "campo", "ordenes"],
    children: [
      {
        key: "agenda",
        label: "Mi agenda",
        icon: "PiCalendarCheckFill",
        wordkeys: ["agenda", "ordenes asignadas", "evidencia", "inventario"],
        roles: [TECHNICIAN_ROLE],
        hideForSuperuser: true,
        path: "/agenda",
      },
    ],
  },
  {
    key: "account",
    label: "Cuenta",
    icon: "PiUserFill",
    wordkeys: ["perfil", "usuario", "cuenta"],
    children: [
      {
        key: "profile",
        label: "Perfil",
        icon: "PiUserFill",
        wordkeys: ["perfil", "usuario", "cuenta"],
        path: "/profile",
      },
    ],
  },
];
