# Generated by Django 4.2.28 on 2026-02-12 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='usuarios.company'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='usuarios.company'),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_numbers', to='usuarios.company'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['company', 'status'], name='service_req_company_382275_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['-created_at'], name='service_req_created_b042a3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'validation_status'], name='customers_company_f2056e_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='customers_phone_91048b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('company', 'phone')},
        ),
        migrations.AddIndex(
            model_name='blacklist',
            index=models.Index(fields=['company', 'phone'], name='blacklist_company_3b0f29_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blacklist',
            unique_together={('company', 'phone')},
        ),
    ]
