# Generated by Django 5.2.8 on 2026-04-10 06:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        ('usuarios', '0003_role_hierarchy_admin_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicLanding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('headline', models.CharField(blank=True, max_length=180)),
                ('subtitle', models.TextField(blank=True)),
                ('cta_text', models.CharField(default='Enviar solicitud', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_landings', to='usuarios.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_public_landings', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_public_landings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'public_landings',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='landing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='clientes.publiclanding'),
        ),
        migrations.AddIndex(
            model_name='publiclanding',
            index=models.Index(fields=['company', 'is_active'], name='public_land_company_0d6c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='publiclanding',
            index=models.Index(fields=['company', 'is_default'], name='public_land_company_d59c77_idx'),
        ),
        migrations.AddIndex(
            model_name='publiclanding',
            index=models.Index(fields=['company', 'slug'], name='public_land_company_b1c104_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='publiclanding',
            unique_together={('company', 'slug')},
        ),
    ]
