# Generated by Django 5.2.8 on 2026-04-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0003_publiclanding_servicerequest_landing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
